network/urls.py
from django.urls import path

from . import views

app_name = "network"
urlpatterns = [
    # Index/All posts web page
    path("", views.index, name="index"),
    # User's profile page
    path("profile/<int:user_id>", views.profile, name="profile"),
    # Posts from following users page
    path("following", views.following, name="following"),
    # Edit posts
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
    # Like posts
    path("like_post/<int:post_id>", views.like_post, name="like_post"),
    # Accounts web pages
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    #API Routes
    path("follow", views.follow, name="follow"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models


class User(AbstractUser):
    """List of registered users"""
    pass

class Post(models.Model):
    """Posts made by users"""
    content = models.TextField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, 
        related_name="posts")
    created_at = models.DateTimeField(auto_now_add=True)

class Follow(models.Model):
    """Relation between users following each other"""
    user_following = models.ForeignKey(User, on_delete=models.CASCADE,
        related_name="following_list")
    user_followed = models.ForeignKey(User, on_delete=models.CASCADE, 
        related_name="followers_list")
    
    def follow_is_valid(self):
        """Following user can't be followed user at the same time"""
        if self.user_following == self.user_followed:
            raise ValidationError(
                "Following and followed can't be the same person")
    
    def __str__(self):
        return f"{self.user_following} is following {self.user_followed}"
    
    class Meta:
        """ Avoid repetetion as each following is unique"""
        unique_together = ("user_following", "user_followed")

class Like(models.Model):
    """Likes made by users on posts"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
        related_name="post_likes")
    
    def __str__(self):
        return f"{self.user} liked post n°{self.post.id}."
        
    class Meta:
        """Avoid repetition as each like yo each post is unique"""
        unique_together = ("user", "post")

network/forms.py
from django import forms

from .models import User, Post

class PostForm(forms.ModelForm):
    """Create a new post"""
    class Meta:
        model = Post
        fields = ["content"]
        labels= {"content": ""}
        widgets = {
            "content": forms.Textarea(attrs={"class": "form-control"}),
        }

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import User, Post, Follow, Like
from .forms import PostForm


def paginate_posts(request, posts):
    """Function to paginate posts"""
    # Paginate
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    return posts

def get_liked_posts(request):
    if request.user.is_authenticated:
        return Like.objects.filter(user=request.user).values_list("post",
            flat=True)
    else: 
        return 

def index(request):
    """Main page, it shows all the posts and it let create a new one"""
    posts = Post.objects.all().order_by("-created_at")
    posts = paginate_posts(request, posts)
    liked_posts = get_liked_posts(request)
    
    # If a post is submited
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = Post(content=form.cleaned_data['content'],
                creator=request.user)
            new_post.save()
            return HttpResponseRedirect(reverse("network:index"))  
    
    # Regular load
    else:  
        form = PostForm()

    return render(request, "network/index.html", {
        "form": form,
        "posts": posts,
        "liked_posts": liked_posts,
    })


def profile(request, user_id):
    """Show profile of a selected user"""
    profile_user = User.objects.get(pk=user_id)
    
    # Determine if request user is following profile user or no
    if profile_user.followers_list.filter(user_following=request.user.id).exists():
        profile_user.is_following = True
    else:
        profile_user.is_following = False
    
    posts = Post.objects.filter(creator=user_id).order_by("-created_at")
    posts = paginate_posts(request, posts)
    liked_posts = get_liked_posts(request)

    return render(request, "network/profile.html", {
        "profile_user": profile_user,
        "posts": posts,
        "liked_posts": liked_posts,
    })


@login_required
def following(request):
    """Show posts from following users"""
    # Get user's following list
    following_list = Follow.objects.filter(
        user_following=request.user.id).values_list("user_followed")
    # Get posts filtered by user's following list
    posts = Post.objects.filter(
        creator__in=following_list).order_by("-created_at")
    posts = paginate_posts(request, posts)
    liked_posts = get_liked_posts(request)

    return render(request, "network/following.html", {
        "posts": posts,
        "liked_posts": liked_posts,
    })


@login_required
def follow(request):
    """Update following button"""
    if request.method == "POST":
        data = json.loads(request.body)
        user_to_follow = User.objects.get(pk=int(data['user_to_follow']))
        # Follow someone
        if data['follow'].strip() == "Follow": 
            follow = Follow(user_following=request.user,
                user_followed=user_to_follow)
            follow.follow_is_valid()
            follow.save()
            message = "Following"
        # Unfollow someone
        else:
            unfollow = Follow.objects.get(user_following=request.user,
                user_followed=user_to_follow)
            unfollow.delete()
            message = "Unfollowing"
        result = {
            "message": message,
        }
        return JsonResponse(result)
    else:
        return JsonResponse({"message": "Method should be POST"})


@login_required
def edit_post(request, post_id):
    """Modify the content of a post"""
    if request.method == "PUT":
        post = Post.objects.get(pk=post_id)
        data = json.loads(request.body)
        post.content = data['content']
        post.save()
        return JsonResponse({"message": "Post modified succesfully"})
    else:
        return JsonResponse({"message": "Method should be PUT"})


@login_required
def like_post(request, post_id):
    """Like or unlike a post"""
    if request.method == "POST":
        post = Post.objects.get(pk=post_id)
        # Like a coment
        try:
            like = Like(user=request.user, post=post)
            like.save()
            message = "liked"
        except IntegrityError:
            like = Like.objects.get(user= request.user, post=post)
            like.delete()
            message = "unliked"

        likes_count = Like.objects.filter(post=post).aggregate(
            Count("id"))["id__count"]
        return JsonResponse({
            "message": message,
            "likesCount": likes_count,
            }) 
    else:
        return JsonResponse({"message": "You should use request method POST"})


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

network/templates/network/following.html
{% extends "network/index.html" %}

{% block title %}Following Posts{% endblock title %}
{% block body_header %}

    <h3>Followed Users' Posts</h3>

{% endblock body_header%}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    
    <div id="post-message"></div>

    {% block body_header %}

        <h3>All Posts</h3>
        {% if user.is_authenticated %}
            <div id="new_post" class="container mb-4 py-2">
                <h4>New Post:</h4>
                <form href="" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class="btn" type="submit" value="Post">
                </form>
            </div>
        {% endif %}

    {% endblock body_header %}
    {% block body_posts %}
    
        {% for post in posts %} 
            <div class="card mb-3 border border-dark rounded" data-postid="{{ post.id }}">
                <div class="card-header pt-2">
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'network:profile' post.creator.id %}">
                                {{ post.creator }}
                            </a>                       
                            <small>{{ post.created_at }}</small>
                        </div>
                    {% if user.is_authenticated and user == post.creator %}
                        <div class="col text-right">
                            <a class="editPost" id="edit-{{ post.id }}" href="#">
                                Edit
                            </a>
                        </div>
                    {% endif %}
                    </div>
                </div>
                <div class="card-body" id="post-{{ post.id }}">
                    <p id="content-{{ post.id }}">{{ post.content }}</p>
                    <div id="form-{{ post.id }}"></div>
                </div>
                <div class="card-body like-container">
                    <span class="mr-1" id="like-{{ post.id }}">
                        ❤️{{ post.post_likes.count }}
                    </span>
                    {% if user.is_authenticated %}
                            {% if post.id in liked_posts %}
                                <img class="like" src="{% static 'network/dislike.svg' %}" alt="Unlike"> 
                                <span class="ml-auto position-relative">Unlike</span>
                            {% else %}
                                <img class="like" src="{% static 'network/like.svg' %}" alt="Like">
                                <span class="ml-auto position-relative">Like</span>
                            {% endif %}
                    {% endif %}
                </div>
            </div>
        {% empty %}
            <p>No posts have been made yet.</p>
        {% endfor%}
            <div class="pagination">
                <span class="step-links">
                    {% if posts.has_previous %}
                        <a id="first" href="?page=1">&laquo; first</a>
                        <a id="previous" href="?page={{ posts.previous_page_number }}">
                            previous
                        </a>
                    {% endif %}
                    <span class="current">
                        Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                    </span>
                    {% if posts.has_next %}
                        <a id="next" href="?page={{ posts.next_page_number }}">
                            next
                        </a>
                        <a id="last" href="?page={{ posts.paginator.num_pages }}">
                            last &raquo;
                        </a>
                    {% endif %}
                </span>
            </div>

    {% endblock body_posts %}
    
{% endblock %}
{% block script %}

    <script src="{% static 'network/index.js' %}"></script>

{% endblock script %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'network/styles.css' %}">
        {% block script %}{% endblock script %}
    </head>
    <body id="body">

        <nav class="navbar navbar-expand-lg navbar-dark mb-4">
            <a class="navbar-brand mr-0" href="{% url 'network:index' %}">
                CS50 Network</a>
            <div class="container-fluid">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}" id="nav-1">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}" id="nav-2">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:profile' request.user.id %}" id="nav-3">Profile</a>
                    </li>
              </ul>
              <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:profile' request.user.id %}"><strong id="username">{{ user.username }}</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}" id="nav-4">Log Out</a>
                    </li>
                {% else %}
              </ul>
              <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}" id="nav-5">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}" id="nav-6">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="container">
            {% block body %}{% endblock body %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h3>Login</h3>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/index.html" %}

{% block title %}Profile{% endblock title %}

{% block body_header %}

    <div>
        <h3><span id="profile-name">{{ profile_user }}</span>'s Profile</h3>
        {% if user.is_authenticated and user != profile_user %}
            <button class="btn" id="follow" name="follow" value="{{ profile_user.id }}">
                {% if profile_user.is_following == True %}
                    Unfollow
                {% else %}
                    Follow
                {% endif %}
            </button>
        {% endif %}
    </div>
    <div> 
        <p class="follow-text">
            <b>Followers: </b><span id="followersCount">
            {{ profile_user.followers_list.count }}</span><b> | Following: </b>
            <span id="followingCount">{{ profile_user.following_list.count }}</span>
        </p>
    </div>

{% endblock body_header %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h3>Register</h3>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}